#!/bin/bash

zettel_folder="/Users/$USER/zettelkasten"
timestamp_zettel=`date +%Y%m%d%H%M%S`
timestamp_today=`date +%Y%m%d`

zettel_path="$zettel_folder/$timestamp_today/$timestamp_zettel.md"
echo $zettel_path

headline="# $1"
quote="> $timestamp_zettel"

mkdir -p "$zettel_folder/$timestamp_today"

# if [ -f $zettel_path ]; then
#     echo "Zettel already exists"
# else
#     echo "Creating zettel"
#     touch $zettel_path
#     echo $headline >> $zettel_path
#     echo $quote >> $zettel_path
#     echo "" >> $zettel_path
# fi

printf "%s\n" "$headline" "$quote" > $zettel_path

vim $zettel_path

cd $zettel_folder
git add "$timestamp_today/$timestamp_zettel.md"
git commit -m "Add $timestamp_zettel to the zettelkasten"
git push -u origin main
cd $current_folder

